# Site settings
title: Welcome to Fox Forum Helper 2.3.3
tag_text: Welcome to Fox Forum Helper 2.3.3
description: The Fox Forum Helper Chrome Extension is a Chrome extension that adds customization to the Fox News Forums.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
