# Site settings
title: Fox Forum Helper Version 1.0
tag_text: Fox Forum Helper Version 1.0
description: The Fox Forum Helper Chrome Extension is a Chrome extension that adds customization to the Fox News Forums.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
