# Site settings
title: Fox Forum Helper Version 2.2.1 Beta
tag_text: Fox Forum Helper Version 2.2.1 Beta
description: The Fox Forum Helper Chrome Extension is a Chrome extension that adds customization to the Fox News Forums.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
